ci: update

diff --git a/.github/workflows/lint-commit-message.yml b/.github/workflows/lint-commit-message.yml
--- a/.github/workflows/lint-commit-message.yml
+++ b/.github/workflows/lint-commit-message.yml
@@ -40,9 +40,13 @@ jobs:
       - name: Install dependencies
         run: pnpm i --frozen-lockfile
 
+      - name: Set PR title as environment variable
+        run: |
+          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
+
       - name: Lint commit
         id: lint_commit
-        run: pnpm lint:commit || echo "failed=true" >> $GITHUB_OUTPUT
+        run: pnpm run lint:commit || echo "failed=true" >> $GITHUB_OUTPUT
 
       - uses: actions-awesome/pr-helper@1.1.1
         with:
@@ -54,7 +58,9 @@ jobs:
 
             你好，@${{ github.event.pull_request.user.login }}，你的提交消息不符合 Element Plus 的提交消息规范。
 
-            ${{ toJSON(steps.lint_commit) }}-${{github.event.pull_request.title}}
+            ${{ toJSON(steps.lint_commit) }}
+
+            ${{github.event.pull_request.title}}
 
             Please refer to [Commit Example](https://element-plus.org/en-US/guide/commit-examples.html) for fixing it.
 
