ci: update

diff --git a/.github/workflows/lint-commit-message.yml b/.github/workflows/lint-commit-message.yml
--- a/.github/workflows/lint-commit-message.yml
+++ b/.github/workflows/lint-commit-message.yml
@@ -40,13 +40,9 @@ jobs:
       - name: Install dependencies
         run: pnpm i --frozen-lockfile
 
-      - name: Set PR title as environment variable
-        run: |
-          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
-
       - name: Lint commit
         id: lint_commit
-        run: pnpm run lint:commit || echo "failed=true" >> $GITHUB_OUTPUT
+        run: echo "${{ github.event.pull_request.title }}" | pnpm run lint:commit || echo "failed=true" >> $GITHUB_OUTPUT
 
       - uses: actions-awesome/pr-helper@1.1.1
         with:
